# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'helloworld.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(845, 577)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.gridLayout_3 = QtWidgets.QGridLayout(self.centralwidget)
        self.gridLayout_3.setObjectName("gridLayout_3")
        self.groupBox = QtWidgets.QGroupBox(self.centralwidget)
        self.groupBox.setObjectName("groupBox")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.groupBox)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.pushButton_serial = QtWidgets.QPushButton(self.groupBox)
        self.pushButton_serial.setObjectName("pushButton_serial")
        self.verticalLayout_2.addWidget(self.pushButton_serial)
        self.pushButton_pcan = QtWidgets.QPushButton(self.groupBox)
        self.pushButton_pcan.setObjectName("pushButton_pcan")
        self.verticalLayout_2.addWidget(self.pushButton_pcan)
        self.pushButton_vcan = QtWidgets.QPushButton(self.groupBox)
        self.pushButton_vcan.setObjectName("pushButton_vcan")
        self.verticalLayout_2.addWidget(self.pushButton_vcan)
        self.gridLayout_3.addWidget(self.groupBox, 0, 0, 1, 1)
        self.groupBox_2 = QtWidgets.QGroupBox(self.centralwidget)
        self.groupBox_2.setObjectName("groupBox_2")
        self.gridLayout = QtWidgets.QGridLayout(self.groupBox_2)
        self.gridLayout.setObjectName("gridLayout")
        self.textBrowser_log_print = QtWidgets.QTextBrowser(self.groupBox_2)
        self.textBrowser_log_print.setObjectName("textBrowser_log_print")
        self.gridLayout.addWidget(self.textBrowser_log_print, 0, 0, 1, 1)
        self.gridLayout_3.addWidget(self.groupBox_2, 0, 1, 1, 1)
        self.groupBox_3 = QtWidgets.QGroupBox(self.centralwidget)
        self.groupBox_3.setObjectName("groupBox_3")
        self.gridLayout_2 = QtWidgets.QGridLayout(self.groupBox_3)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.webView_map = QtWebKitWidgets.QWebView(self.groupBox_3)
        self.webView_map.setUrl(QtCore.QUrl("about:blank"))
        self.webView_map.setObjectName("webView_map")
        self.gridLayout_2.addWidget(self.webView_map, 0, 0, 1, 1)
        self.gridLayout_3.addWidget(self.groupBox_3, 1, 1, 1, 1)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 845, 22))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)
        self.action12 = QtWidgets.QAction(MainWindow)
        self.action12.setObjectName("action12")

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "Hello wen."))
        self.groupBox.setTitle(_translate("MainWindow", "权限赋予"))
        self.pushButton_serial.setText(_translate("MainWindow", "串口赋权"))
        self.pushButton_pcan.setText(_translate("MainWindow", "pcan赋权"))
        self.pushButton_vcan.setText(_translate("MainWindow", "vcan赋权"))
        self.groupBox_2.setTitle(_translate("MainWindow", "日志输出"))
        self.groupBox_3.setTitle(_translate("MainWindow", "地图展示"))
        self.action12.setText(_translate("MainWindow", "12"))
from PyQt5 import QtWebKitWidgets
